using System;
using System.Collections.Generic;
using System.Text.Json;
using Autodesk.AutoCAD.Colors;
using Autodesk.AutoCAD.DatabaseServices;
using Autodesk.AutoCAD.Geometry;
using Autodesk.Civil;
using Autodesk.Civil.DatabaseServices;

namespace Civil3DMcpBridge.Tools;

/// <summary>
/// Vehicle-tracking proxies (Civil-3D-native). These approximate swept-path
/// analysis inside Civil 3D — a lateral <c>envelope</c> generated by walking
/// an alignment at inner / outer offsets, and a single-arc <c>turning path</c>
/// alignment from a design radius. True AVTW swept-path compliance checking
/// (per-vehicle templates, mountable kerb check) lives in Autodesk Vehicle
/// Tracking, a separate host — see docs/AUTOMATION_RECIPES.md.
/// </summary>
internal static class TrackingTools
{
    public static void Register()
    {
        ToolRegistry.Register("civil3d_swept_path_envelope", SweptPathEnvelope);
        ToolRegistry.Register("civil3d_create_turning_path_arc", CreateTurningPathArc);
    }

    /// <summary>
    /// Args:
    /// {
    ///   "alignment": "string", "start_station": number, "end_station": number,
    ///   "left_offset": number, "right_offset": number,   // envelope edges (positive = left)
    ///   "step": number (default 0.5),
    ///   "layer": "string" (default "C-TRACK-ENVELOPE"), "color_aci": int (default 2)
    /// }
    /// </summary>
    private static object SweptPathEnvelope(JsonElement args)
    {
        var alignmentName = args.GetRequiredString("alignment");
        var startStation = args.GetRequiredDouble("start_station");
        var endStation = args.GetRequiredDouble("end_station");
        var leftOffset = args.GetRequiredDouble("left_offset");
        var rightOffset = args.GetRequiredDouble("right_offset");
        var step = args.GetOptionalDouble("step", 0.5);
        var layer = args.GetOptionalString("layer") ?? "C-TRACK-ENVELOPE";
        var colorAci = args.GetOptionalInt("color_aci", 2);

        if (endStation <= startStation) throw new ToolException("'end_station' must be > 'start_station'");
        if (step <= 0) throw new ToolException("'step' must be positive");

        var (doc, civDoc) = DrawingContext.RequireActive();
        using var docLock = doc.LockDocument();
        using var tr = doc.Database.TransactionManager.StartTransaction();

        var al = AlignmentTools.FindAlignmentByName(tr, civDoc, alignmentName)
            ?? throw new ToolException($"alignment '{alignmentName}' not found");
        GeometryHelpers.ValidateStation(al, startStation);
        GeometryHelpers.ValidateStation(al, endStation);

        var ms = (BlockTableRecord)tr.GetObject(
            SymbolUtilityServices.GetBlockModelSpaceId(doc.Database), OpenMode.ForWrite);
        EnsureLayer(tr, doc.Database, layer);

        var inner = DrawSide(tr, ms, al, startStation, endStation, leftOffset, step, layer, colorAci);
        var outer = DrawSide(tr, ms, al, startStation, endStation, rightOffset, step, layer, colorAci);

        tr.Commit();
        return new
        {
            alignment = alignmentName,
            startStation,
            endStation,
            leftOffset,
            rightOffset,
            envelopeWidth = Math.Abs(leftOffset - rightOffset),
            innerVertices = inner,
            outerVertices = outer,
            layer,
        };
    }

    /// <summary>
    /// Single-arc turning-path alignment.
    /// Args: { center_x, center_y, radius, start_angle_deg, end_angle_deg, name, description? }
    /// </summary>
    private static object CreateTurningPathArc(JsonElement args)
    {
        var cx = args.GetRequiredDouble("center_x");
        var cy = args.GetRequiredDouble("center_y");
        var radius = args.GetRequiredDouble("radius");
        var startDeg = args.GetRequiredDouble("start_angle_deg");
        var endDeg = args.GetRequiredDouble("end_angle_deg");
        var name = args.GetRequiredString("name");
        var description = args.GetOptionalString("description");

        if (radius <= 0) throw new ToolException("radius must be positive");

        var (doc, civDoc) = DrawingContext.RequireActive();
        using var docLock = doc.LockDocument();
        using var tr = doc.Database.TransactionManager.StartTransaction();

        var ms = (BlockTableRecord)tr.GetObject(
            SymbolUtilityServices.GetBlockModelSpaceId(doc.Database), OpenMode.ForWrite);

        double a0 = startDeg * Math.PI / 180.0;
        double a1 = endDeg * Math.PI / 180.0;
        while (a1 <= a0) a1 += 2 * Math.PI;   // force CCW sweep
        double sweep = a1 - a0;
        int steps = Math.Max(2, (int)Math.Ceiling(sweep / (Math.PI / 36.0))); // ≤5° per vertex

        var pl = new Polyline();
        for (var i = 0; i <= steps; i++)
        {
            double a = a0 + sweep * i / steps;
            pl.AddVertexAt(i,
                new Point2d(cx + radius * Math.Cos(a), cy + radius * Math.Sin(a)), 0, 0, 0);
        }
        ms.AppendEntity(pl);
        tr.AddNewlyCreatedDBObject(pl, true);

        var options = new PolylineOptions
        {
            PlineId = pl.ObjectId,
            AddCurvesBetweenTangents = false,
            EraseExistingEntities = true,
        };
        ObjectId alId;
        try
        {
            alId = Alignment.Create(civDoc, options, name, ObjectId.Null, ObjectId.Null, ObjectId.Null, ObjectId.Null);
        }
        catch (Autodesk.AutoCAD.Runtime.Exception ex)
        {
            pl.Erase();
            throw new ToolException($"could not create turning-path alignment: {ex.Message}");
        }

        var al = (Alignment)tr.GetObject(alId, OpenMode.ForWrite);
        if (!string.IsNullOrEmpty(description)) al.Description = description;

        tr.Commit();
        return new
        {
            name = al.Name,
            radius,
            startAngleDeg = startDeg,
            endAngleDeg = endDeg,
            arcLength = radius * sweep,
            alignmentLength = al.Length,
            handle = al.Handle.Value.ToString("x"),
        };
    }

    private static int DrawSide(Transaction tr, BlockTableRecord ms, Alignment al,
        double startStation, double endStation, double offset, double step,
        string layer, int colorAci)
    {
        var pl = new Polyline();
        int idx = 0;
        for (var s = startStation; s < endStation; s += step)
        {
            double e = 0, n = 0;
            al.PointLocation(s, offset, ref e, ref n);
            pl.AddVertexAt(idx++, new Point2d(e, n), 0, 0, 0);
        }
        double ex = 0, nx = 0;
        al.PointLocation(endStation, offset, ref ex, ref nx);
        pl.AddVertexAt(idx, new Point2d(ex, nx), 0, 0, 0);
        pl.Layer = layer;
        pl.Color = Color.FromColorIndex(ColorMethod.ByAci, (short)colorAci);
        ms.AppendEntity(pl);
        tr.AddNewlyCreatedDBObject(pl, true);
        return idx + 1;
    }

    private static void EnsureLayer(Transaction tr, Database db, string layerName)
    {
        var lt = (LayerTable)tr.GetObject(db.LayerTableId, OpenMode.ForWrite);
        if (lt.Has(layerName)) return;
        var newLayer = new LayerTableRecord { Name = layerName };
        lt.Add(newLayer);
        tr.AddNewlyCreatedDBObject(newLayer, true);
    }
}
